# Generated by Django 4.1.5 on 2023-01-17 19:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('reason', models.CharField(choices=[('wedding', 'Свадьба'), ('birthday', 'День рождения'), ('no_reason', 'Без повода')], db_index=True, default='no_reason', max_length=20, verbose_name='Событие')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('composition', models.TextField(blank=True, verbose_name='Состав букета')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Высота')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Высота')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Букет',
                'verbose_name_plural': 'Букеты',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(db_index=True, max_length=200, verbose_name='ФИО клиента')),
                ('phonenumber', models.CharField(max_length=20, verbose_name='Номер клиента')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Когда создан запрос')),
                ('closed', models.BooleanField(db_index=True, default=False, verbose_name='Консультация проведена')),
                ('comment', models.TextField(blank=True, verbose_name='Заметки по клиенту')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(db_index=True, max_length=200, verbose_name='ФИО клиента')),
                ('phonenumber', models.CharField(max_length=20, verbose_name='Номер клиента')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='backend.bouquet', verbose_name='Букет')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
