# Generated by Django 4.1.5 on 2023-01-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_order_address_order_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payed',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
