# Generated by Django 4.1.5 on 2023-01-18 21:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_order_payed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='closed',
            new_name='is_closed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payed',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Доставлено'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_payed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(choices=[('ASAP', 'Как можно скорее'), ('10:00-12:00', '10:00-12:00'), ('12:00-14:00', '12:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00')], default='ASAP', max_length=15, verbose_name='Время доставки'),
        ),
    ]
