# Generated by Django 4.1.5 on 2023-01-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_closed_consultation_is_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидает'), ('in progress', 'В работе'), ('rejection', 'Отказ от заказа'), ('done', 'Заказ оформлен')], db_index=True, default='waiting', max_length=20, verbose_name='Статус работы'),
        ),
    ]
