# Generated by Django 4.1.5 on 2023-01-19 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_consultation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='is_closed',
        ),
    ]
