# Generated by Django 4.1.5 on 2023-01-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_order_yookassa_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='color_hye',
            field=models.CharField(blank=True, choices=[('pink', 'Розовый'), ('white', 'Белый'), ('red', 'Красный'), ('yellow', 'Жёлтый'), ('purple', 'Фиолетовый')], max_length=15, null=True, verbose_name='Цветовая гамма'),
        ),
    ]
