# Generated by Django 4.1.5 on 2023-01-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_order_consultation_consultation_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Статистика консультации',
                'verbose_name_plural': 'Статистика консультаций',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.consultation',),
        ),
    ]
