# Generated by Django 4.1.5 on 2023-01-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_bouquet_color_hye'),
        ('backend', '0014_alter_order_is_delivered'),
    ]

    operations = [
    ]
